stages:
  - static analysis
  - build
  
jobs:
  include:
    - stage: "static analysis"      
      name: "cppcheck"         
      script:
      - sudo apt-get update -qq
      - sudo apt-get install -qq cppcheck
      - cppcheck --quiet --error-exitcode=1 . 

    - stage: "unit tests"
      name: "cpputest"
      script:
      - git clone git://github.com/cpputest/cpputest.git
      - cd cpputest
      - cd cpputest_build
      - autoreconf .. -i
      - ../configure
      - make -j
      - cp -r lib ../lib
      - export CPPUTEST_HOME=cpputest
      - cd tests && make -jobs
      
    - stage: "build"      
      name: "compile"         
      script: 
       - gcc test.c -o test
       - ./test
 
