language : c
compiler : gcc
before_install:
  - sudo apt-get update -qq
install: 
  # cppcheck
  - sudo apt-get install -qq cppcheck

  -stage: "Compile"
   name: "Compile"
   script: 
   - gcc test.c -o test
   - ./test
