jobs:
  include:
    - stage: "static_analysis"      
      name: "Cppcheck"         
      script:
      - sudo apt-get update -qq
      - sudo apt-get install -qq cppcheck
      - cppcheck --quiet --error-exitcode=1 . 
      
    - stage: "build"      
      name: "compile"         
      script: 
       - gcc test.c -o test
       - ./test
 
